Задание 1
h31/ProgrammingLabSummer2020Task1 pull request #1
Opened 2020-02-11 21:48 UTC by Br0mm

Задание 1. Вариант 17.
Написал класс и тесты для него, продолжаю выполнять часть бонуса.
Название методам поворота граней дал согласно стандартному языку поворотов Кубика Рубика (http://www.rubiksplace.com/www.rubiksplace.com/move-notations/)

2020-02-12 19:03 UTC, h31 requested changes

2020-02-12 19:03 UTC, h31 commented on src/MyProject/Cube.java
> +    Cube(int n) {
Если класс `public`, то и конструктор тоже логично сделать `public`. Иначе получается, что класс вроде как публичный, но создать объект класса вы не можете, так как конструктор недоступен.

2020-02-12 19:03 UTC, h31 commented on src/MyProject/Cube.java
> +    private static String[][] front;
Не думаю, что `String` - самый подходящий тип данных. Строки используются, когда нам нужно хранить тексты, т.е. что-то, состоящее из символов и имеющее переменную длину. В задаче же нужно хранить один из шести цветов, да и переменная длина тут не очень нужна. Есть идеи, какой тип данных подойдет лучше?

2020-02-12 19:03 UTC, h31 commented on src/MyProject/Cube.java
> +                front[i][j] = "\u001B[31m" + "▮"; //Red
Хотелось бы увидеть комментарий по поводу того, зачем нужны эти константы вида `\u001B...`. Я знаю, откуда они взялись, но вдруг код будет читать человек, который не знает про подобные константы?

2020-02-12 19:03 UTC, h31 commented on src/MyProject/Cube.java
> +                front[i][j] = "\u001B[31m" + "▮"; //Red
Кроме того, в коде сейчас смешаны логика и представление. Другими словами, класс для кубика Рубика не должен знать о том, как выводить цвета на консоль. А если у нас графическая программа? А если веб-сервис? В каждом случае для отображения цвета используются разные средства. Естественно, каждый раз переделывать класс под новый вид UI - не очень хорошая идея.

2020-02-12 19:03 UTC, h31 commented on src/MyProject/Cube.java
> +    private static String[][] front;
Почему все поля `static`?

2020-02-12 19:03 UTC, h31 commented on src/MyProject/Cube.java
> +
Не хватает стандартных методов - toString, equals, hashCode.

2020-02-12 19:03 UTC, h31 commented on src/MyProject/Cube.java
> +    public static void r(int k) {
Лучше использовать более длинные и понятные имена, чтобы не искать в справочнике расшифровку действия

2020-02-12 19:03 UTC, h31 commented on src/MyProject/Cube.java
> +            for (int i = 1; i < 4; i++) {
`4` можно вынести как константу, потому что она довольно много где используется

2020-02-12 19:03 UTC, h31 commented on test/MyProject/CubeTest.java
> +    void turns() {
Я не понимаю, что происходит в тестах. Что-то делается, но что именно и что при этом проверяется - непонятно.

2020-02-12 19:03 UTC, h31 commented on test/MyProject/CubeTest.java
> +            assert true;
Выражение `assert true` не имеет смысла, оно ничего не делает

2020-02-13 21:13 UTC, Br0mm commented on src/MyProject/Cube.java
> +
Добавил

2020-02-13 21:13 UTC, Br0mm commented on test/MyProject/CubeTest.java
> +    void turns() {
Написал комментарии к тестам

2020-02-13 21:13 UTC, Br0mm commented on src/MyProject/Cube.java
> +    Cube(int n) {
Поправил

2020-02-13 21:14 UTC, Br0mm commented on src/MyProject/Cube.java
> +    private static String[][] front;
Изменил тип на enum. Убрал static

2020-02-13 21:14 UTC, Br0mm commented on src/MyProject/Cube.java
> +                front[i][j] = "\u001B[31m" + "▮"; //Red
Заменил тип на enum

2020-02-13 21:14 UTC, Br0mm commented on src/MyProject/Cube.java
> +    public static void r(int k) {
Поменял имена

2020-02-13 21:15 UTC, Br0mm commented on src/MyProject/Cube.java
> +            for (int i = 1; i < 4; i++) {
Вынес как константу

2020-02-13 21:15 UTC, Br0mm commented on test/MyProject/CubeTest.java
> +            assert true;
Убрал

2020-02-29 15:22 UTC, h31 requested changes
Оцениваю работу на 5. Исправьте замечания, и поставлю оценку.

2020-02-29 15:22 UTC, h31 commented on src/main/java/MyProject/Cube.java
> +    //Методы поворотов кубика (Язык поворотов кубика стандартный), чтобы указать какое "кольцо" надо поворачивать
Комментарии к методам лучше писать в стандартном формате JavaDoc. Посмотрите, например, как они оформлены в Котоеде.

2020-02-29 15:22 UTC, h31 commented on src/main/java/MyProject/Cube.java
> +    private Colour[][] rotate (Colour[][] face) {
Лишний пробел, из-за этого не сразу смог найти метод в коде. Не забывайте делать `Reformat`.

2020-02-29 15:22 UTC, h31 commented on src/main/java/MyProject/Cube.java
> +            for (int i = 1; i < repeats; i++) {
Получается, мы поворачиваем грань три раза? Если так, то это просто поворот один раз в другую сторону. Как я вижу, подобный цикл применяется не один раз в программе, так что есть смысл вынести его в отдельный метод. Т.е. речь не о том, чтобы делать отдельный метод для поворота в другую сторону, а в том, чтобы просто перенести существующий код в отдельный метод.

2020-02-29 15:22 UTC, h31 commented on src/main/java/MyProject/Cube.java
> +        if (k == 0) right = rotate(right);
Я не очень понимаю, почему мы обрабатываем только два варианта - `k == 0` и `k == size`. А промежуточные?

2020-02-29 15:22 UTC, h31 commented on src/main/java/MyProject/Cube.java
> +    private void pifPuf() {
Алгоритмы лучше вынести в отдельный класс. Зачастую в больших классах сложно сориентироваться, поэтому рекомендуется разбивать их на несколько небольших.

2020-02-29 15:22 UTC, h31 commented on src/main/java/MyProject/Cube.java
> +        rightFaceClockwise(0);
Я не понимаю, почему где-то аргумент `0`, а где-то `1`. Можно ли сделать код более наглядным? Например, использовать enum или как-нибудь реструктуризировать методы.

2020-02-29 15:22 UTC, h31 commented on src/main/java/MyProject/Cube.java
> +    private void placingMiniCube(Colour colour1, Colour colour2) {
В некоторых моментах код можно сделать более удобочитаемым. Что такое миникубики? Чем отличается `colour1` от `colour2`?

2020-02-29 15:22 UTC, h31 commented on src/main/java/MyProject/Cube.java
> +    private void placingMiniCube(Colour colour1, Colour colour2) {
Если берете откуда-то алгоритм решения, не забывайте оставлять ссылку. Без этого понять логику работы кода довольно сложно.

2020-02-29 15:22 UTC, h31 commented on src/main/java/MyProject/Cube.java
> +        other.turnUp();
Во-первых, `equals` - это просто операция сравнения. Естественно ожидать, что сравнение не будет как-либо менять один из операндов. Поэтому было странно увидеть операцию поворота в коде.

Во-вторых, насколько я понимаю, вы хотите, чтобы одинаковые по содержимому, но по-разному развернутые кубы считались равными. Идея интересная, но я не думаю, что такие кубы можно считать равными, потому что одинаковые операции над ними дадут различный результат.

2020-02-29 15:22 UTC, h31 commented on src/main/java/MyProject/Cube.java
> +    public Colour[][] status() {
Стоит уточнить, что мы запрашиваем именно фронтальную грань.

2020-02-29 15:22 UTC, h31 commented on src/main/java/MyProject/Cube.java
> +    private Colour[][] rotate (Colour[][] face) {
Есть два разных подхода к тому, как могут выполняться модифицирующие операции. Можно создавать копию данных и оперировать ею (как сейчас сделано в `rotate`), либо можно изменять данные на месте (как сделано в `frontFaceClockwise` и других методах). Оба подхода имеют свои плюсы и минусы. Например, с минусами вы столкнулись в `equals`. Изучите этот вопрос, решите для себя, когда какой подход лучше использовать. В идеале, конечно, хотелось бы унификации по всему классу. И помните, что если изменяете данные на месте, нужна операция копирования объекта (конструктор или метод), чтобы можно было безопасно оперировать с объектом, например, в тестах.

2020-02-29 15:22 UTC, h31 commented on src/main/java/MyProject/Cube.java
> +        turnDown();
См. замечание к `equals`

2020-02-29 15:22 UTC, h31 commented on src/test/java/MyProject/CubeTest.java
> +    //тесты для проверки правильности equals() (проверка "чёрным ящиком")
Тесты белого и черного ящика лучше разнести в два отдельных тестовых класса

2020-03-01 18:55 UTC, Br0mm commented on src/main/java/MyProject/Cube.java
> +        if (k == 0) right = rotate(right);
В промежуточных вариантах поворачивается только определённое кольцо, а при этих двух случаях поворачивается не только кольцо но и грань, поэтому содержимое этой грани надо повернуть.

2020-03-01 19:17 UTC, Br0mm commented on src/main/java/MyProject/Cube.java
> +    //Методы поворотов кубика (Язык поворотов кубика стандартный), чтобы указать какое "кольцо" надо поворачивать
Поправил

2020-03-01 19:48 UTC, Br0mm commented on src/main/java/MyProject/Cube.java
> +            for (int i = 1; i < repeats; i++) {
Поправил

2020-03-01 19:52 UTC, Br0mm commented on src/main/java/MyProject/Cube.java
> +    private void placingMiniCube(Colour colour1, Colour colour2) {
Написал и оставил ссылки на алгоритм

2020-03-01 19:52 UTC, Br0mm commented on src/main/java/MyProject/Cube.java
> +        other.turnUp();
Поправил

2020-03-01 19:53 UTC, Br0mm commented on src/main/java/MyProject/Cube.java
> +    public Colour[][] status() {
Поправил

2020-03-01 19:53 UTC, Br0mm commented on src/main/java/MyProject/Cube.java
> +        turnDown();
Поправил

2020-03-01 19:53 UTC, Br0mm commented on src/test/java/MyProject/CubeTest.java
> +    //тесты для проверки правильности equals() (проверка "чёрным ящиком")
Поправил

2020-03-01 19:55 UTC, Br0mm commented on src/main/java/MyProject/Cube.java
> +    private void pifPuf() {
Решил сделать данные методы более универсальными и подходящими для любого кубика, и решил добавить возможность вызвать их, потому что это стандартные методы для сборок различных кубиков.

2020-03-01 19:59 UTC, Br0mm commented on src/main/java/MyProject/Cube.java
> +    private Colour[][] rotate (Colour[][] face) {
Сделал реформат кода

2020-03-02 16:58 UTC, h31 commented
Принято

2020-03-02 16:58 UTC, closed without merging