AddressBook
h31/ProgrammingLabSummer2020Task1 pull request #2
Opened 2020-02-12 19:16 UTC by OGSegu

2020-02-13 21:43 UTC, h31 requested changes

2020-02-13 21:43 UTC, h31 commented on src/main/java/AddressBook.java
> +import javafx.util.Pair;
Если вы не пользуетесь JavaFX в проекте, то лучше не использовать классы из него

2020-02-13 21:43 UTC, h31 commented on src/main/java/AddressBook.java
> +        for (int i = 0; i != people.length; i++) {
Можно заменить на for each

2020-02-13 21:43 UTC, h31 commented on src/main/java/AddressBook.java
> +        if (!map.containsKey(surname)) throw new NullPointerException();
Уверены, что `NullPointerException` - подходящий тип исключения?

2020-02-13 21:43 UTC, h31 commented on src/main/java/AddressBook.java
> +    AddressBook changeAdds(String surname, Address address) {
Что такое `Adds`? Есть ли смысл так сильно сокращать?

2020-02-13 21:43 UTC, h31 commented on src/main/java/AddressBook.java
> +    List<String> filterHouse(String street, String house) {
`Building`, скорее

2020-02-13 21:43 UTC, h31 commented on src/main/java/AddressBook.java
> +    boolean equals(Address address) {
Не хватает стандартных методов - toString, hashCode. В `AddressBook`не хватает их же + equals.

2020-02-14 08:32 UTC, OGSegu commented on src/main/java/AddressBook.java
> +import javafx.util.Pair;
JavaFX используется для класса Pair.

2020-02-14 08:33 UTC, OGSegu commented on src/main/java/AddressBook.java
> +    AddressBook changeAdds(String surname, Address address) {
Смотрел в Гугл переводчик, это стандартное сокращение от Address

2020-02-15 10:36 UTC, OGSegu commented
Все исправил.

2020-03-01 20:44 UTC, h31 requested changes
Пока только часть комментариев, остальное допишу позже

2020-03-01 20:44 UTC, h31 commented on src/main/java/AddressBook.java
> +import javafx.util.Pair;
JavaFX - это опциональный компонент, в новых версиях JVM его может не быть. Если вам нужен ещё один класс для каких-то целей, то можно просто создать его самому.

2020-03-01 20:44 UTC, h31 commented on src/main/java/AddressBook.java
> +class AddressBook {
Почему решили сделать класс package-private, а не public?

2020-03-01 20:44 UTC, h31 commented on src/main/java/AddressBook.java
> +    AddressBook changeAdds(String surname, Address address) {
Не вижу смысла в этом сокращении. Что именно вы экономите таким образом? Несколько символов? У IDE есть автодополнение, так что вам не придется набирать больше.

2020-03-01 20:44 UTC, h31 commented on src/main/java/AddressBook.java
> +        if (!map.containsKey(surname)) throw new NullPointerException();
Почему именно `NullPointerException`?

2020-03-16 11:43 UTC, h31 requested changes

2020-03-16 11:43 UTC, h31 commented on src/main/java/AddressBook.java
> +    private HashMap<String, Address> map = new HashMap<>();
В качестве типа можно указать просто `Map<String, Address>`, по аналогии с тем, как делается в случае `List`.

2020-03-16 11:43 UTC, h31 commented on src/main/java/AddressBook.java
> +    AddressBook(Pair ... people) {
Класс стал `public`, а методы и конструкторы остались со старой областью видимости

2020-03-16 11:43 UTC, h31 commented on src/main/java/AddressBook.java
> +        if (!map.containsKey(surname)) throw new IllegalArgumentException();
Можно обойтись без `containsKey`. Посмотрите, что возвращает `remove`. Аналогично и в других методах

2020-03-16 11:43 UTC, h31 commented on src/main/java/Main.java
> +public class Main {
Лишний файл

2020-03-16 11:43 UTC, h31 commented on src/main/java/Pair.java
> +public class Pair {
Забыли про стандартные методы

2020-03-16 11:43 UTC, h31 commented on src/main/java/AddressBook.java
> +import java.util.*;
По ряду причин использование пакета по умолчанию - это bad practice

2020-03-16 11:43 UTC, h31 commented on src/test/java/AddressBookTest.java
> +    @Test(expected = NullPointerException.class)
У вас в коде выбрасывается `IllegalArgumentException`, нет? Тест вообще работает?

2020-03-16 11:43 UTC, h31 commented on src/test/java/AddressBookTest.java
> +    private static AddressBook createDictionary() {
Вполне нормальный способ, но можно сделать по-другому - поле класса с выражением инициализации. Для каждого тестового метода это поле будет инициализироваться заново (как и весь класс). Исправлять не нужно, просто FYI.

2020-03-16 15:14 UTC, OGSegu commented on src/test/java/AddressBookTest.java
> +    private static AddressBook createDictionary() {
Все исправил!

2020-03-16 18:35 UTC, h31 commented
Пару вещей забыл отметить (например, `add`, который никак не показывает, перезаписали ли мы слово или добавили новое), но код в целом весьма хороший. Принято, оценка 5.

2020-03-16 18:35 UTC, closed without merging