Гасилов Дмитрий. Вариант 11(Прейскурант)
h31/ProgrammingLabSummer2020Task1 pull request #4
Opened 2020-02-16 10:28 UTC by KoTTiG

2020-03-01 10:44 UTC, h31 requested changes

2020-03-01 10:44 UTC, h31 commented on src/main/java/PriceList/PriceList.java
> +    }
Где-то между методами есть пустая строка, где-то её нет. Не забывайте делать Reformat.

2020-03-01 10:44 UTC, h31 commented on pom.xml
> +            <artifactId>testng</artifactId>
Вы где-то используете testng?

2020-03-01 10:44 UTC, h31 commented on src/main/java/PriceList/PriceList.java
> +    public PriceList add(Item newItem, Double price) {
Почему решили использовать Double для хранения цены?

2020-03-01 10:44 UTC, h31 commented on src/main/java/PriceList/PriceList.java
> +    PriceList() {
Если класс `public`, то и конструктор логично сделать таким же, иначе вы не сможете создать объект. Бывают ситуации, когда специально делают приватные конструкторы, но это исключительные случаи.

2020-03-01 10:44 UTC, h31 commented on src/main/java/PriceList/PriceList.java
> +    public PriceList add(String name,Integer id, Double price) {
Форматирование

2020-03-01 10:44 UTC, h31 commented on src/main/java/PriceList/PriceList.java
> +        for (Item item: items.keySet()) {
Основной плюс HashMap - быстрый поиск элемента в коллекции. Но поиском вы в классе не пользуетесь, вместо этого используя перебор. Либо смените тип коллекции, либо уберите перебор. Желательно, конечно, убрать перебор.

2020-03-01 10:44 UTC, h31 commented on src/main/java/PriceList/PriceList.java
> +                "items=" + items +
Если у нас в классе только одно поле, зачем нам писать `"items="`?

2020-03-01 10:44 UTC, h31 commented on src/test/java/PriceList/PriceListTest.java
> +    public void itemGetName() {
Тесты для Item логично вынести в отдельный класс

2020-03-01 10:44 UTC, h31 commented on src/test/java/PriceList/PriceListTest.java
> +    public void changeName() {
Мы проверяем ошибочные сценарии использования, а что насчет корректного?

2020-03-01 10:44 UTC, h31 commented on src/main/java/PriceList/PriceList.java
> +        items.put(newItem, Math.floor(price*100)/100);
Зачем здесь нужно округление?

2020-03-01 14:09 UTC, KoTTiG commented on src/main/java/PriceList/PriceList.java
> +    public PriceList add(Item newItem, Double price) {
Я решил, что с помощью Double можно отобразить цену в Рублях (целая часть) и копейках (дробная часть), как и требовалось в задании. По этому же я использовал округление, потому что копейки измеряются в диапазоне от 0 до 99

2020-03-01 14:15 UTC, KoTTiG commented on src/main/java/PriceList/PriceList.java
> +    public PriceList add(Item newItem, Double price) {
Я решил использовать Double, потому что по заданию цена должна быть представлена в рублях (целая часть) и копейках (дробная часть), так же по этому я использовал округление до сотых ,потому что копейки находятся в диапазоне от 0 до 99

2020-03-16 16:06 UTC, h31 requested changes

2020-03-16 16:06 UTC, h31 commented on src/main/java/PriceList/PriceList.java
> +    private ArrayList<Item> items;
Почему `ArrayList`, а не просто `List`?

2020-03-16 16:06 UTC, h31 commented on src/main/java/PriceList/PriceList.java
> +        items = new ArrayList<Item>();
Инициализацию можно перенести в ту же строчку, где и объявлена переменная

2020-03-16 16:06 UTC, h31 commented on src/main/java/PriceList/PriceList.java
> +class Item {
Почему методы `public`, а класс - нет?

2020-03-16 16:06 UTC, h31 commented on src/main/java/PriceList/PriceList.java
> +    private Double price;
По поводу https://github.com/h31/ProgrammingLabSummer2020Task1/pull/4#discussion_r386111611 .

Во-первых, `Double` и `double` - это разные типы в Java. Посмотрите, в чем разница между ними. Как правило, используют `double`.

Во-вторых, double устроен так, что не может точно представить некоторые значения, например, 0.1. Ошибки могут накапливаться и влиять на результат, поэтому не рекомендуется использовать этот тип для финансовых данных. Вам об этом либо уже рассказывали, либо будут рассказывать в других курсах, но если не знали об этом, то стоит почитать самому.

2020-03-16 16:06 UTC, h31 commented on src/main/java/PriceList/PriceList.java
> +        id = newId;
Что будет, если `newId` окажется равен -1? Или имя окажется пустым? Или цена отрицательной?

2020-03-16 16:06 UTC, h31 commented on src/main/java/PriceList/PriceList.java
> +    private ArrayList<Item> items;
В продолжение https://github.com/h31/ProgrammingLabSummer2020Task1/pull/4#discussion_r386096356 . Как я вижу, решили всё-таки оставить перебор. Имейте в виду, что решение с List неоптимальное, поэтому мне придется несколько снизить оценку.

2020-03-16 16:06 UTC, h31 commented on src/main/java/PriceList/PriceList.java
> +    public PriceList changeName(String oldName, String newName) {
Можно ли устранить дублирование между двумя вариантами `changeName`, двумя вариантами `remove` и т.д.?

2020-03-16 16:06 UTC, h31 commented on src/main/java/PriceList/PriceList.java
> +    public double getPrice(String name) {
Если ли метод для определения цены покупки по коду и количеству экземпляров?

2020-03-16 16:06 UTC, h31 commented on src/main/java/PriceList/PriceList.java
> +    public PriceList add(String name, Integer id, Double price) {
Вы нигде в тестах не используете method chaining. В чем тогда смысл возвращать `PriceList`? Было бы более логично, например, возвращать информацию о том, был ли добавлен новый элемент или заменен существующий.

2020-03-16 16:06 UTC, h31 commented on src/test/java/PriceList/PriceListTest.java
> +        assertEquals(newTest.toString(), test.changeName(1, "name").toString());
Зачем тут `toString`?

2020-03-16 18:02 UTC, KoTTiG commented on src/main/java/PriceList/PriceList.java
> +    private ArrayList<Item> items;
Если я правильно понял, то в Джаве нет просто `List`, есть две его реализации `LinkedList` и `ArrayList`

2020-03-16 18:30 UTC, KoTTiG commented on src/main/java/PriceList/PriceList.java
> +        id = newId;
Отрицательные значения цены и `newId` и пустая строка в качестве имени не вызывают каких-либо ошибок, так что мне кажется, что будет так же, как и при обычных значениях

2020-03-16 19:11 UTC, h31 commented on src/main/java/PriceList/PriceList.java
> +    private ArrayList<Item> items;
`List` есть. Это интерфейс, т.е. нельзя написать `new List`. Но как тип его можно использовать.

2020-03-16 19:13 UTC, h31 commented on src/main/java/PriceList/PriceList.java
> +        id = newId;
Ошибок они не вызывают, но это очевидно некорректные значения (как минимум, в случае с ценой)

2020-03-16 21:43 UTC, KoTTiG commented on src/main/java/PriceList/PriceList.java
> +    public PriceList add(String name, Integer id, Double price) {
Не совсем понимаю, какой практический смысл от информации о том, был заменен элемент или добавлен новый, но если так правильнее,  то как это реализовать ? Возвращать True\false в зависимости от результата ?

2020-03-17 08:35 UTC, KoTTiG commented on src/main/java/PriceList/PriceList.java
> +    public double getPrice(String name) {
Определение цены по коду есть, а о каком количестве экземпляров идет речь я не совсем понял, потому что в самом задании о прейскуранте о нем не было указано, но при этом оно появилось в одном методе,

2020-03-17 08:40 UTC, KoTTiG commented on src/main/java/PriceList/PriceList.java
> +    public PriceList changeName(String oldName, String newName) {
Не понимаю, как это сделать, ведь от того, что подается на вход (название товара или его код) зависит порядок действий

2020-03-17 22:41 UTC, KoTTiG commented on src/main/java/PriceList/PriceList.java
> +    private Double price;
Я изменил представление цены в виде двух `int`: один для "Рублей", другой для "Копеек", но это решение мне кажется каким-то небрежным, но я пока не могу придумать другого, так же есть возможность вынести цену и методы связанные с ней в отдельный класс, но нужно ли так дробить программу на настолько мелкие классы ?

2020-03-20 22:06 UTC, h31 commented on src/main/java/PriceList/PriceList.java
> +    public double getPrice(String name) {
![image](https://user-images.githubusercontent.com/3375923/77209491-6fa53180-6b0f-11ea-82ef-8670c05fd01c.png)
Имеется в виду, что на входе следующие данные:

* Морковка, 1 штука
* Гречка, 10 пачек
* Туалетная бумага, 20 штук

Имея данные о стоимости каждого товара в прейскуранте, мы можем посчитать итоговую стоимость покупки данного набора.
Под входными данными я имею в виду структуру, а не формат. Не нужно делать их строкой.

2020-03-20 22:39 UTC, h31 commented on src/main/java/PriceList/PriceList.java
> +    private Double price;
Сделать отдельный класс - хорошая идея. В большинстве случаев вынесение части программы в отдельный класс или отдельный метод повышает удобочитаемость кода. Понятно, что во всем должен быть здравый смысл, есть определенная граница, после которой дробить программу неразумно, но в данном случае всё в порядке.

Идея с `int` правильная. По поводу того, что для денег не стоит использовать `double` есть много информации, например, [неплохая статья](https://habr.com/ru/post/338108/). Возможно, вам уже рассказывали об этом на курсе информатики. По поводу сомнений в качестве кода - попробуйте сделать отдельный класс, это должно исправить проблему. Другой вариант - использовать один `int`, храня цену в копейках. Тут тоже будет хорошей идеей создать отдельный класс, так как работать с таким представлением неудобно. Третий вариант - использовать класс `BigDecimal`. В любом случае, хотелось бы, чтобы пользователя вашего класса не сильно затрагивали детали хранения, чтобы у него был удобный интерфейс для добавления товара.

2020-03-20 22:59 UTC, h31 commented on src/main/java/PriceList/PriceList.java
> +    public PriceList changeName(String oldName, String newName) {
Можно сделать метод, который бы по названию товара или по коду искал бы `Item`. В таком случае `changeName` будет выглядеть примерно так:
```
var item = getItem(oldName);
item.changeName(newName);
```
Или даже
```
var item = getItem(oldName);
changeName(item, newName);
```
(changeName для `Item` - единственная перегрузка, где содержится непосредственно код для изменения имени)

2020-03-20 23:16 UTC, h31 commented on src/main/java/PriceList/PriceList.java
> +    public PriceList add(String name, Integer id, Double price) {
Потому что это позволяет как-то сообщать о происходящем. Когда данные молча перезаписываются - это плохо. У нас нет возможности спросить у вызывающего кода "Вы уверены, что хотите перезаписать данные?". Мы, конечно, можем запретить перезапись и выбрасывать исключение в подобных случаях, но это может усложнить использование класса. Тут нет готового рецепта, как лучше делать, всё сильно зависит от конкретного случая. Я предложил компромиссный вариант с возвращаемым значением, потому что так, например, делает `Map`. В его же описании можно посмотреть, как именно это реализовано.

2023-09-11 07:56 UTC, closed without merging