Quaternion
h31/ProgrammingLabSummer2020Task1 pull request #5
Opened 2020-02-17 19:12 UTC by kechinvv

kechin.vv FirstVersion

2020-03-04 23:40 UTC, h31 requested changes

2020-03-04 23:40 UTC, h31 commented on src/main/java/quaternion/Quaternion.java
> +    public double[] get() {
Если это определение оси и угла поворота, то стоит подумать над названием метода, сейчас оно практически ничего не говорит о методе

2020-03-04 23:40 UTC, h31 commented on src/main/java/quaternion/Quaternion.java
> +        if (abs(this.norm()) < 10e-10) throw new ArithmeticException();
Почему именно `10e-10`?

2020-03-04 23:40 UTC, h31 commented on src/test/java/Quaternion/TestQ.java
> +        assertEquals(a.w, b.w, 10e-5);
Почему `10e-5`?

2020-03-04 23:40 UTC, h31 commented on src/main/java/quaternion/Quaternion.java
> +    Quaternion() {
Могу предположить, что конструктор использовался в начале разработки, но сейчас оказался ненужен. В таком случае его лучше удалить.

2020-03-06 16:22 UTC, kechinvv commented on src/main/java/quaternion/Quaternion.java
> +        if (abs(this.norm()) < 10e-10) throw new ArithmeticException();
Изменил все погрешности на 1е-5, так как в тестах в прошлом семестре указывалась именно такая погрешность

2020-03-06 16:25 UTC, kechinvv commented on src/main/java/quaternion/Quaternion.java
> +    public double[] get() {
Переименовал на getAngleAxis

2020-03-06 16:26 UTC, kechinvv commented on src/main/java/quaternion/Quaternion.java
> +    Quaternion() {
Конструктор использовался в тестах для создания нулевого кватерниона, но я убрал его и стал создавать их через задания параметра.

2020-03-16 01:39 UTC, h31 commented
Принято. Оценка 5

2020-03-16 01:39 UTC, closed without merging